name: user_bundle

services:
  php:
    image: idmarinas/php:8.2-xdebug
    environment:
      SYMFONY_REQUIRE: '6.4.*'
    healthcheck:
      test: php -v || exit 1
    volumes:
      - ./:/var/www/html
      ## SSH
      - .docker/php/key_ssh/id_rsa:/root/.ssh/id_rsa:ro
      ## PHP Conf
      - ./.docker/php/conf.d/date_timezone.ini:/usr/local/etc/php/conf.d/date_timezone.ini

  mailer:
    image: axllent/mailpit
    ports:
      - "1080:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
