# https://github.com/actions/deploy-pages#usage
name: Deploy Docs to GitHub Pages

on:
  release:
    types: [ published ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
      - name: Get repository name
        id: repo
        shell: bash
        run: echo "name=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: bun install
      - name: Static HTML export with Nuxt
        run: NUXT_APP_BASE_URL=/${{ steps.repo.outputs.name }}/ bunx nuxt generate --preset github_pages
      - run: rm -f .output/public/.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/.output/public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
